title: My Great Title
theme: minima
author: B User
date: 2021-12-21

email: your-email@domain.com
description: what is this to edit this des
what's description how can i add 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

