title: "My Great Title"
theme: minima
author: B User
date: 2021-12-21
email: your-email@domain.com
description: what is this to edit this des
what's description how can i add 

# social links
twitter_username: my Twitter
github_username:  my Github

show_excerpts: false
